GET http://localhost:4000/users

###

POST http://localhost:4000/users
Content-Type:  application/json

{
   "name":"yaani tu" ,
   "email":"76546@example.com",
   "password":"password", 
   "phoneNumber": "074439342"
   
}


###

POST http://localhost:4000/users/login
Content-Type:  application/json

{
   "email":"maryjoy@example.com",
   "password":"maryjoy"
   
}
###

POST http://localhost:9000/users/login
Content-Type:  application/json

{
    "email": "maryjoy@example.com",
   "password":"maryjoy"
   
}

###

GET http://localhost:4000/users/07937f89-e8ee-4ec5-94f9-5af3b62a9d84

###
GET http://localhost:4000/users/email/example123@example.com

###
DELETE  http://localhost:4000/users/1ac24f89-f1be-439e-91e4-eb7055fb2879

###
PUT http://localhost:4000/users/7848a6a2-5373-4695-836b-5b139d07a559
Content-Type:  application/json

{
   "name":"Mary NNMwangiii" ,
   "email":"marUU@gmail.com",
   "password":"123RYUR478",
   "phoneNumber": "077234555"
   
}


###
POST http://localhost:4000/products
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMWMyNzFkLTk0ZDAtNDFiYi1hZTRjLWM5MzlhMWUxZWMyZCIsIm5hbWUiOiJUZXN0R3V5MSIsImVtYWlsIjoidGVzdDNAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzEyMzk0MDc4LCJyb2xlIjoidXNlciIsImlhdCI6MTY4Mzk2NzMxOSwiZXhwIjoxNjg0MzI3MzE5fQ.JgrjrfQT0hMgJYngMBQ8mywk3GgaInwDFsCOQXsFxck

{
"productName":"watch:)", 
"inStock":200,
"price":5000,
"image":"string",
"description":"a very good watch"
}

###
GET http://localhost:4000/products

###
GET http://localhost:4000/products/560d5c81-e6a6-41a8-b50b-7b86fc8d183f

###
PUT http://localhost:4000/products/560d5c81-e6a6-41a8-b50b-7b86fc8d183f
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMWMyNzFkLTk0ZDAtNDFiYi1hZTRjLWM5MzlhMWUxZWMyZCIsIm5hbWUiOiJUZXN0R3V5MSIsImVtYWlsIjoidGVzdDNAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzEyMzk0MDc4LCJyb2xlIjoidXNlciIsImlhdCI6MTY4Mzk2NzMxOSwiZXhwIjoxNjg0MzI3MzE5fQ.JgrjrfQT0hMgJYngMBQ8mywk3GgaInwDFsCOQXsFxck


{
"productName":"Clock", 
"inStock":25080,
"price":6050,
"image":"string",
"description":"avery good watch"
}


###
DELETE http://localhost:9000/products/66b011b4-3fb4-4b26-890f-bfc048fe9f5b
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5YmFjMDRiLWM3YmItNDk0Mi05ZDRhLWNjMGI0ZWM3NDI3MiIsIm5hbWUiOiJNYXJ5am95IiwiZW1haWwiOiJtYXJ5am95QGV4YW1wbGUuY29tIiwicGhvbmVOdW1iZXIiOjcxMjk0NTY3OCwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgzOTY3NDU3LCJleHAiOjE2ODQzMjc0NTd9.bBKC26BwzIA6Jh90eLAhZB9mcNB3dluc_11zr7YQPjM


###
//add to cart

POST http://localhost:9000/cart/50bc3edc-ea9e-4c31-9462-f8f314ebfd4a
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMWMyNzFkLTk0ZDAtNDFiYi1hZTRjLWM5MzlhMWUxZWMyZCIsIm5hbWUiOiJUZXN0R3V5MSIsImVtYWlsIjoidGVzdDNAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzEyMzk0MDc4LCJyb2xlIjoidXNlciIsImlhdCI6MTY4NDA0ODU2MSwiZXhwIjoxNjg0NDA4NTYxfQ.2vkCv_wJ0p43As3fy0Juq4gBzhz1NRU_alHm9eryOnU


####
//
GET  http://localhost:9000/cart/7b1c271d-94d0-41bb-ae4c-c939a1e1ec2d

######

PUT  http://localhost:9000/cart/50bc3edc-ea9e-4c31-9462-f8f314ebfd4a
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMWMyNzFkLTk0ZDAtNDFiYi1hZTRjLWM5MzlhMWUxZWMyZCIsIm5hbWUiOiJUZXN0R3V5MSIsImVtYWlsIjoidGVzdDNAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzEyMzk0MDc4LCJyb2xlIjoidXNlciIsImlhdCI6MTY4NDA0ODU2MSwiZXhwIjoxNjg0NDA4NTYxfQ.2vkCv_wJ0p43As3fy0Juq4gBzhz1NRU_alHm9eryOnU



####
PUT http://localhost:9000/cart/cart/50bc3edc-ea9e-4c31-9462-f8f314ebfd4a
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMWMyNzFkLTk0ZDAtNDFiYi1hZTRjLWM5MzlhMWUxZWMyZCIsIm5hbWUiOiJUZXN0R3V5MSIsImVtYWlsIjoidGVzdDNAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzEyMzk0MDc4LCJyb2xlIjoidXNlciIsImlhdCI6MTY4NDA0ODU2MSwiZXhwIjoxNjg0NDA4NTYxfQ.2vkCv_wJ0p43As3fy0Juq4gBzhz1NRU_alHm9eryOnU

