GET http://localhost:4000/users

###

POST http://localhost:4000/users
Content-Type:  application/json

{
   "name":"test user 101" ,
   "email":"alexmaingi077@gmail.com",
   "password":"password", 
   "phoneNumber": "0715475235"
   
}


###

POST http://localhost:4000/users/login
Content-Type:  application/json

{
   "email":"76546@example.com",
   "password":"admin"
   
}
###

POST http://localhost:4000/users/login
Content-Type:  application/json

{
    "email": "maryjoy@example.com",
   "password":"password"
   
}

###

GET http://localhost:4000/users/07937f89-e8ee-4ec5-94f9-5af3b62a9d84

###
GET http://localhost:4000/users/email/marrrryjoy@example.com

###
DELETE  http://localhost:4000/users/d8553946-19d0-491f-a1e4-23612db6a2c6

###
PUT http://localhost:4000/users/ba39dffa-08bf-48c3-910a-618ce18ba20a
Content-Type:  application/json

{
   "name":"test user 101" ,
   "email":"testUser@example.com",
   "password":"password", 
   "phoneNumber": "074739359"
   
}

//-----------------------PRODUCTS-----------------

###
POST http://localhost:4000/products
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5YTBmZDQ0LTg5NzEtNDQ0NC04NzEzLWUyOWFkMjQwOThlMyIsIm5hbWUiOiJtYXJ5am95IGZyIiwiZW1haWwiOiJtYXJ5am95QGV4YW1wbGUuY29tIiwicGhvbmVOdW1iZXIiOjc0NTM5MzU5LCJyb2xlIjoidXNlciIsImlhdCI6MTY4NDMyNTc3NywiZXhwIjoxNjg0Njg1Nzc3fQ.i6r3ixHIG-cdFohS9H0EwP6sVsTadAEXjanGc6LswYg

{
"productName":"unga", 
"inStock":200,
"price":5000,
"image":"string",
"description":"utashiba"
}

###
GET http://localhost:4000/products

###
GET http://localhost:4000/products/2bf24f4f-8e62-45c5-8c1b-577f25ee4ce3
###
PUT http://localhost:4000/products/83db2eb6-26ea-454a-9826-72480a2a46c0
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5YTBmZDQ0LTg5NzEtNDQ0NC04NzEzLWUyOWFkMjQwOThlMyIsIm5hbWUiOiJtYXJ5am95IGZyIiwiZW1haWwiOiJtYXJ5am95QGV4YW1wbGUuY29tIiwicGhvbmVOdW1iZXIiOjc0NTM5MzU5LCJyb2xlIjoidXNlciIsImlhdCI6MTY4NDMyNTc3NywiZXhwIjoxNjg0Njg1Nzc3fQ.i6r3ixHIG-cdFohS9H0EwP6sVsTadAEXjanGc6LswYg


{
"productName":"Clock", 
"inStock":25080,
"price":6050,
"image":"string",
"description":"avery good watch"
}



###
DELETE http://localhost:4000/products/83db2eb6-26ea-454a-9826-72480a2a46c0
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5YTBmZDQ0LTg5NzEtNDQ0NC04NzEzLWUyOWFkMjQwOThlMyIsIm5hbWUiOiJtYXJ5am95IGZyIiwiZW1haWwiOiJtYXJ5am95QGV4YW1wbGUuY29tIiwicGhvbmVOdW1iZXIiOjc0NTM5MzU5LCJyb2xlIjoidXNlciIsImlhdCI6MTY4NDMyNTc3NywiZXhwIjoxNjg0Njg1Nzc3fQ.i6r3ixHIG-cdFohS9H0EwP6sVsTadAEXjanGc6LswYg



//------------------------------------CART------------------------------------------------

//put an item to cart, uses product_id in url and user_id in the token
###
//add to cart


POST http://localhost:4000/cart/2bf24f4f-8e62-45c5-8c1b-577f25ee4ce3
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZmFhZGY3LTAxNWMtNDNkZC05NjM4LTM2NmZiYzIwYjg3YyIsIm5hbWUiOiJ5YWFuaSB0dSIsImVtYWlsIjoiNzY1NDZAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzQ0MzkzNDIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NTM2MzUyNCwiZXhwIjoxNjg1NzIzNTI0fQ.aE_E7BEbTnW2xGsVsxpJV99AnHTcNKIH-EHi5vtAkdo



//get everything in the user's cart -pass user id in the url
####

GET  http://localhost:4000/cart/d1faadf7-015c-43dd-9638-366fbc20b87c
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZmFhZGY3LTAxNWMtNDNkZC05NjM4LTM2NmZiYzIwYjg3YyIsIm5hbWUiOiJ5YWFuaSB0dSIsImVtYWlsIjoiNzY1NDZAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzQ0MzkzNDIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDk0OTI0OSwiZXhwIjoxNjg1MzA5MjQ5fQ.V9nkIKgP7HRte0Xaspk8_tQA4knnj8AMZjhW6H8i7X8



//delete item in cart takes in cart_id in url, confirms if it belongs to user (via token) then deletes

######

PUT  http://localhost:4000/cart/589c11ab-217d-4ff3-80ac-129ecd7c62fd
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5YTBmZDQ0LTg5NzEtNDQ0NC04NzEzLWUyOWFkMjQwOThlMyIsIm5hbWUiOiJtYXJ5am95IGZyIiwiZW1haWwiOiJtYXJ5am95QGV4YW1wbGUuY29tIiwicGhvbmVOdW1iZXIiOjc0NTM5MzU5LCJyb2xlIjoidXNlciIsImlhdCI6MTY4NDMxODczNiwiZXhwIjoxNjg0Njc4NzM2fQ.HpPOFhQtUO6azpqkEjGFff9mXpKY9w76VJiisNtDdLE


######
//decrement item count in cart takes cart_id in url and user token 
PUT  http://localhost:4000/cart/decrement/6
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZmFhZGY3LTAxNWMtNDNkZC05NjM4LTM2NmZiYzIwYjg3YyIsIm5hbWUiOiJ5YWFuaSB0dSIsImVtYWlsIjoiNzY1NDZAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzQ0MzkzNDIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDA5NjM5MSwiZXhwIjoxNjg0NDU2MzkxfQ.BmvZxlZln975RBrB_W4cnYJIFFZJRORTfyDFUg-10TE

###
//increment item count in cart 
PUT  http://localhost:4000/cart/increment/e82ebe6d-3a6b-4563-acfd-e093784ac9d0
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZmFhZGY3LTAxNWMtNDNkZC05NjM4LTM2NmZiYzIwYjg3YyIsIm5hbWUiOiJ5YWFuaSB0dSIsImVtYWlsIjoiNzY1NDZAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzQ0MzkzNDIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDQxMzQ2MywiZXhwIjoxNjg0NzczNDYzfQ.aU2EDZVdrNJ7LubKhugM3AD0nn4X2LwOuqRGMJGVRUc

//------------------------------------ORDERS--------------------------------------------------
//get order by a certain user using order_id in url and user token to know which user
###
GET http://localhost:4000/order/ec8067a3-86d9-4ecd-bb1d-cf86a6eb9565
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZmFhZGY3LTAxNWMtNDNkZC05NjM4LTM2NmZiYzIwYjg3YyIsIm5hbWUiOiJ5YWFuaSB0dSIsImVtYWlsIjoiNzY1NDZAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzQ0MzkzNDIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NTM2MzUyNCwiZXhwIjoxNjg1NzIzNTI0fQ.aE_E7BEbTnW2xGsVsxpJV99AnHTcNKIH-EHi5vtAkdo


//make order using user_id
###
POST http://localhost:4000/order/d1faadf7-015c-43dd-9638-366fbc20b87c

//cancel an order using the order id in the url
###
PUT http://localhost:4000/order/delete/882e7ac8-8d7c-4148-bca9-7ab91d03c353
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZmFhZGY3LTAxNWMtNDNkZC05NjM4LTM2NmZiYzIwYjg3YyIsIm5hbWUiOiJ5YWFuaSB0dSIsImVtYWlsIjoiNzY1NDZAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzQ0MzkzNDIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NTM2MzUyNCwiZXhwIjoxNjg1NzIzNTI0fQ.aE_E7BEbTnW2xGsVsxpJV99AnHTcNKIH-EHi5vtAkdo

//get all orders, only for admin
###
GET http://localhost:4000/order
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZmFhZGY3LTAxNWMtNDNkZC05NjM4LTM2NmZiYzIwYjg3YyIsIm5hbWUiOiJ5YWFuaSB0dSIsImVtYWlsIjoiNzY1NDZAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzQ0MzkzNDIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDk0OTI0OSwiZXhwIjoxNjg1MzA5MjQ5fQ.V9nkIKgP7HRte0Xaspk8_tQA4knnj8AMZjhW6H8i7X8


//mark as dispatched, only for admin
###
PUT http://localhost:4000/order/dispatched/30a2fff4-129b-41ee-b65b-f5be8a25c59b
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5YTBmZDQ0LTg5NzEtNDQ0NC04NzEzLWUyOWFkMjQwOThlMyIsIm5hbWUiOiJtYXJ5am95IGZyIiwiZW1haWwiOiJtYXJ5am95QGV4YW1wbGUuY29tIiwicGhvbmVOdW1iZXIiOjc0NTM5MzU5LCJyb2xlIjoidXNlciIsImlhdCI6MTY4NDQxODI0MCwiZXhwIjoxNjg0Nzc4MjQwfQ.yMPl5mVb8iQVMebJ4sDlhFxHEk74d0fr4oI3gdIb_DE


//mark as delivered, only for admin
###
PUT http://localhost:4000/order/delivered/a0a97872-1dae-4b1d-8055-5a0871ed2b81
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZmFhZGY3LTAxNWMtNDNkZC05NjM4LTM2NmZiYzIwYjg3YyIsIm5hbWUiOiJ5YWFuaSB0dSIsImVtYWlsIjoiNzY1NDZAZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6NzQ0MzkzNDIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDM1MDAyOSwiZXhwIjoxNjg0NzEwMDI5fQ.FAizRbcfuEGxMuo8MRhESCuZBN18iqQdRuUbpnPRXfk


//--------------------forgot password
###
GET http://localhost:4000/users/forgotPassword/alexmaingi077@gmail.com



//RESET password

####
PUT http://localhost:4000/users/forgotPassword/reset/d1faadf7-015c-43dd-9638-366fbc20b87c
Content-Type:  application/json

{
     "email":"76546@example.com",
   "password":"admin"
   
}